[build]
command = "npm run build"
publish = ".next"

[[d1_databases]]
binding = "DB"
database_name = "guoqi-meeting-db"
database_id = "96a402e2-c146-486e-a497-616590825577"

[build.environment]
NODE_VERSION = "20"
